import type { Metadata } from "next";
import "./globals.css";
import Provider from "@/provider";
import Header from "@/components/shared/Header";
import Container from "@/components/container/Container";
import Footer from "@/components/shared/Footer";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-50">
        <Header />
        <main>
          <Container>
            <Provider>{children}</Provider>
          </Container>
        </main>
        <Footer />
      </body>
    </html>
  );
}
